/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_idreamsky_fanbook_common_ucrop_task_FBBitmapCropTask */

#ifndef _Included_com_idreamsky_fanbook_common_ucrop_task_FBBitmapCropTask
#define _Included_com_idreamsky_fanbook_common_ucrop_task_FBBitmapCropTask
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_idreamsky_fanbook_common_ucrop_task_FBBitmapCropTask
* Method:    cropCImg
* Signature: (Ljava/lang/String;Ljava/lang/String;IIIIF)Z
*/
JNIEXPORT jboolean JNICALL Java_com_idreamsky_fanbook_common_ucrop_task_FBBitmapCropTask_cropCImg
(JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jfloat, jfloat, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
